### ISSUE TITLE
Handle `+build.x` properly

### ISSUE THREAD

**Issue by dietmarw** [xogeny/impact#51] opened 2014-01-27 11:46 UTC
Currently the versions as seen by *impact* include the `+build.x` part not just for listing the available versions (which is fine) but also for installation. 

The problems are:
1. When a user does `impact install Modelica#3.2.1` nothing is getting installed since *impact* expects the complete version number including the `+build.x` part.
2. Dependencies in library only state the version number without any build.

Solution: 
When a users does `impact install Modelica#3.2.1` simply install the latest available build and the same also when a version number is given as dependency. Still keep the functionality to explicitly state a to be installed build number.

**Comment by xogeny** [comment] 2015-04-19 20:01
Duplicate of #83.

**Closed by xogeny** 2015-04-19 20:01 UTC
Labels: duplicate
